apiVersion: v1
kind: Service
metadata:
  name: fastapi-quickstart-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fastapi-quickstart-deploy
  sessionAffinity: None
  type: ClusterIP

