apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Developer Tools
    tekton.dev/displayName: YQ replace
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: yq
  name: yq
  labels:
    app.kubernetes.io/version: '0.3'
spec:
  description: >-
    This task can be used to replace fields in YAML files. For example for
    altering helm charts on GitOps repos.
  params:
    - description: >-
        A list of files to execute the expression on. Needs to be relative to
        the source workspace.
      name: files
      type: array
    - description: The yq expression to apply. Can be used to replace yaml fields.
      name: expression
      type: string
    - default: >-
        docker.io/mikefarah/yq:4.16.2@sha256:0d4f6e27bdcac7316f635acd524ab0eecc4ad50834b54d10322268650c7712cb
      description: The yq image to use.
      name: image
      type: string
  steps:
    - args:
        - '$(params.files[*])'
      image: $(params.image)
      name: replace-in-yaml
      resources: {}
      script: |
        /usr/bin/env sh
        set -e

        for var in "$@"
        do
            /usr/bin/yq eval -i "$(params.expression)" "$var"
        done
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: A workspace that contains the file which needs to be altered.
      name: source

